USE menudb;
﻿CREATE TABLE mytable(wkd VARCHAR(16) NOT NULL PRIMARY KEY,Mon VARCHAR(38),Tue VARCHAR(25),Wed VARCHAR(28),Thu VARCHAR(23),Fri VARCHAR(26),Sat VARCHAR(21),Sun VARCHAR(26));
INSERT INTO mytable(DAY,Mon,Tue,Wed,Thu,Fri,Sat,Sun) VALUES ('FRUIT','Sweet Lime/Banana','Papaya/Banana','Water melon/Banana','Pears/Banana','Sarda/Banana','Mix Fruit/Banana','Papaya/Banana');
INSERT INTO mytable(DAY,Mon,Tue,Wed,Thu,Fri,Sat,Sun) VALUES ('Cereal','Flavoured Flakes/Porridge','Chocos/Porridge','Flavoured Flakes /Porridge','Chocos /Porridge','Flavoured Flakes /Porridge','Chocos /Porridge','Flavoured Flakes /Porridge');
INSERT INTO mytable(DAY,Mon,Tue,Wed,Thu,Fri,Sat,Sun) VALUES ('Egg Preperation','Boiled Egg','Cheese Omelette','French Toast','N/A','Masala Omelette','Boiled Egg','Akuri');
INSERT INTO mytable(DAY,Mon,Tue,Wed,Thu,Fri,Sat,Sun) VALUES ('Indian Bfast','Poha','Idli/Vada/Sambar','Suji Upma','Aloo Pyaaz Prantha','Pav/Bhaji','Grill Chesse Mayo S/W','Kulcha / Matter');
INSERT INTO mytable(DAY,Mon,Tue,Wed,Thu,Fri,Sat,Sun) VALUES ('Choice of milk','Hot/Cold','Hot/Cold','Hot/Cold','Hot/Cold','Hot/Cold','Hot/Cold','Hot/Cold');
INSERT INTO mytable(DAY,Mon,Tue,Wed,Thu,Fri,Sat,Sun) VALUES ('Accompaniment','Coconut Chutney','Coconut Chutney','Tomato Chutney','Pickle','Chopped Onion','Tomato Ketchup','Chopped Onion Green Chilli');
INSERT INTO mytable(DAY,Mon,Tue,Wed,Thu,Fri,Sat,Sun) VALUES ('Hot beverage','Tea /Coffee','Tea/Coffee','Tea/Coffee','Tea/Coffee','Tea/Coffee','Tea/Coffee','Tea/Coffee');
INSERT INTO mytable(DAY,Mon,Tue,Wed,Thu,Fri,Sat,Sun) VALUES ('Bread/Butter/Jam','Bread/Butter/Jam','Bread/Butter/Jam','Bread/Butter/Jam','Bread/Butter/Jam','Bread/Butter/Jam','Bread/Butter/Jam','Bread/Butter/Jam');
INSERT INTO mytable(DAY,Mon,Tue,Wed,Thu,Fri,Sat,Sun) VALUES ('LUNCH',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO mytable(DAY,Mon,Tue,Wed,Thu,Fri,Sat,Sun) VALUES ('Raita/Soup','Roohafza','Boondi Raita','Khas Sharbat','Butter Milk','Cucumber and Onion Raita','Orange Crush','Pineapple Raita');
INSERT INTO mytable(DAY,Mon,Tue,Wed,Thu,Fri,Sat,Sun) VALUES ('SALAD','Salad Bar','Salad Bar','Salad Bar','Salad Bar','Salad Bar','Salad Bar','Salad Bar');
INSERT INTO mytable(DAY,Mon,Tue,Wed,Thu,Fri,Sat,Sun) VALUES ('Composite Salad','Crispy Noodles Salad','Greek Yogurt Salad','Tabulleh Salad','Beetroot salad','Sirka Onion','Ceaser Salad','Gratted Raw Papaya Salad');
INSERT INTO mytable(DAY,Mon,Tue,Wed,Thu,Fri,Sat,Sun) VALUES ('DAL','Rajma Masala','Black Dal','Triveni Dal','Dal Haryali','Kadhi Pakora','Black Channa','Dal Makhani');
INSERT INTO mytable(DAY,Mon,Tue,Wed,Thu,Fri,Sat,Sun) VALUES ('Healthy / Conti','Roasted Eggplant with garlic and herbs','Veg in Hot Garlic Sauce','Penne Pasta In Pesto Sauce','Mangolian Veg','Paneer Jodhpuri','Veg au Gratin','Keema matter');
INSERT INTO mytable(DAY,Mon,Tue,Wed,Thu,Fri,Sat,Sun) VALUES ('DRY VEG','Mutter Mushroom','Achari Veg','Mutter Paneer','Arbi Ajwaini','Aloo Jeera','Subz Meloni','Veg Kofta Curry');
INSERT INTO mytable(DAY,Mon,Tue,Wed,Thu,Fri,Sat,Sun) VALUES ('NON VEG','N/A','N\A','Madras Chicken Curry','N/A','Chicken Biryani','N/A','N\A');
INSERT INTO mytable(DAY,Mon,Tue,Wed,Thu,Fri,Sat,Sun) VALUES ('RICE','Steam rice','Plain Rice','Jeera Fried Rice','Plain Rice','Steam Rice','Onion Pulao','Plain Rice');
INSERT INTO mytable(DAY,Mon,Tue,Wed,Thu,Fri,Sat,Sun) VALUES ('ROTI','Chapati','Chapati','Chapati','Chapati','Chapati','Chapati','Chapati');
INSERT INTO mytable(DAY,Mon,Tue,Wed,Thu,Fri,Sat,Sun) VALUES ('SWEET','Fruit Custard','Paysum',NULL,'Chocolate Mousse',NULL,'Ice Cream','Coconut Burfi');
INSERT INTO mytable(DAY,Mon,Tue,Wed,Thu,Fri,Sat,Sun) VALUES ('SNACKS',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO mytable(DAY,Mon,Tue,Wed,Thu,Fri,Sat,Sun) VALUES ('Snack','Stuffed Bun','Samosa','Tofu Roll','Sprouts & Corn Masala','Sweet Potato Chaat','Oats Muffin','Tofu Roll');
INSERT INTO mytable(DAY,Mon,Tue,Wed,Thu,Fri,Sat,Sun) VALUES ('Accompaniment','Tomato Ketchup','Mint & Saunth Chutney','Tomato Ketchup','Chat Masala','Mint & Saunth Chutney','Tomato Ketchup','Mint Chutney');
INSERT INTO mytable(DAY,Mon,Tue,Wed,Thu,Fri,Sat,Sun) VALUES ('Tea/Coffee','Tea/Cold Coffee','Tea/ Cold Coffee','tea /Lemon Water','Ice Tea/Coffee','Tea/Coffee','Tea/Thandai','Tea/Coffee');
INSERT INTO mytable(DAY,Mon,Tue,Wed,Thu,Fri,Sat,Sun) VALUES ('DINNER',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO mytable(DAY,Mon,Tue,Wed,Thu,Fri,Sat,Sun) VALUES ('Raita/Soup','Masala Chaas','Ginger Garlic Noodle Soup','Tomato Rasam','Cream of Mushroom Soup','Lemon Water','Hot & Saur Soup','Aam Panna');
INSERT INTO mytable(DAY,Mon,Tue,Wed,Thu,Fri,Sat,Sun) VALUES ('SALAD','Salad Bar','Salad Bar','Salad Bar','Salad Bar','Salad Bar','Salad Bar','Salad Bar');
INSERT INTO mytable(DAY,Mon,Tue,Wed,Thu,Fri,Sat,Sun) VALUES ('Composite Salad','Brocolli and Lettuce Salad','Cucumber Sesame Salad','Bruschetta Pasta Salad','Aloo Chana Chaat','Macroni Salad','Kachumber Salad','Carrot Peanut Salad');
INSERT INTO mytable(DAY,Mon,Tue,Wed,Thu,Fri,Sat,Sun) VALUES ('DAL','Channa Dal','Cholle Amritsari','Lobhiya  Dal','Mix Dal','Yellow Dal Tadka','Dal Pakwan','Red Malka');
INSERT INTO mytable(DAY,Mon,Tue,Wed,Thu,Fri,Sat,Sun) VALUES ('GRAVY VEG','Aloo Tamatar','Veg Spaghetti','Soya Matar Masala','Methi Gutta Curry','Chole Amritsari','Aloo Gobhi Adraki','Palak Paneer');
INSERT INTO mytable(DAY,Mon,Tue,Wed,Thu,Fri,Sat,Sun) VALUES ('DRY VEG','Sev Tomatri','Bhindi Kurkuri','Undhiyo','Aloo Pyaaz Bhaja','Andhra Veg Curry','Palak Corn','Mix Veg');
INSERT INTO mytable(DAY,Mon,Tue,Wed,Thu,Fri,Sat,Sun) VALUES ('NON VEG','N/A','N/A','N/A','Egg Curry','N/A','N/A','Fish Curry');
INSERT INTO mytable(DAY,Mon,Tue,Wed,Thu,Fri,Sat,Sun) VALUES ('RICE','Peas Pulao','Bellpepper Rice','Plain Rice','Motiya Pulao','Steam Rice','Herbs Rice','Plain Rice');
INSERT INTO mytable(DAY,Mon,Tue,Wed,Thu,Fri,Sat,Sun) VALUES ('ROTI','Chapatti','Roti','Ghiya Thepla','Malabar Parantha','Roti','Chapatti','Chapatti');
INSERT INTO mytable(DAY,Mon,Tue,Wed,Thu,Fri,Sat,Sun) VALUES ('SWEET',NULL,NULL,'Pastry',NULL,'Besan Laddoo',NULL,'~');
