# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 14:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.CharField(max_length=2)),
                ('location', models.CharField(max_length=50)),
                ('status', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Monday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=5)),
                ('number', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='info',
            name='number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RoomBooking.Monday'),
        ),
    ]
