# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomBooking', '0002_auto_20171019_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monday',
            name='selection',
            field=models.NullBooleanField(),
        ),
    ]
