# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomBooking', '0003_auto_20171019_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monday',
            name='selection',
            field=models.CharField(max_length=5),
        ),
    ]
